spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklib?useSSL=false
    username: root
    password: Vitylin97
  jpa:
    hibernate:
      ddl-auto: none

sites:
- url: 'http://www.playback.ru/'
  name: 'Playback.ru'

User-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
frontendPath: '/admin'